# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-09 13:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=32, null=True)),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('introduction', models.CharField(blank=True, max_length=256, null=True)),
                ('author', models.CharField(blank=True, max_length=32, null=True)),
                ('comment', models.CharField(blank=True, max_length=256, null=True)),
                ('scan', models.IntegerField(default=0)),
                ('photo', models.CharField(blank=True, max_length=32, null=True)),
                ('status', models.CharField(default='normal', max_length=16)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('build_time', models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 9, 13, 1, 48, 171000, tzinfo=utc), null=True)),
            ],
        ),
    ]
